### ISSUE TITLE
Consider ways to minify asset pipeline.

### ISSUE THREAD

**Issue by eskfung** [kissmetrics/km-support#40]
Sass, Less, Google Closure

**Comment by mattysads** [comment]
We have asset minification in another GH-pages project under the query api. We can talk sometime if you want

**Comment by eskfung** [comment]
:cool: :birthday:

**Comment by eskfung** [comment]
Summary: use plugins to generate the css files locally and commit them. Pretty much exactly how `sitemap.xml` is currently under revision control.

### `_config.yml`

```
sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: true
```

### `Gemfile`

```
...
gem 'jekyll-sass'
gem 'bourbon'
```

### `_plugins/whatever.rb`

```
require 'jekyll-sass'
require 'bourbon'
```

For JS, this could be done similarly with coffeescript or closure gems.
